services:
    notebook:
      build: .
      container_name: notebook
      user: root
      restart: always
      environment:
        - GRANT_SUDO=yes
      ports:
        - "8888:8888"
      volumes:
        - ${PROJECT_ROOT}/notebooks:/home/jovyan/work